# Generated by Django 5.0.3 on 2024-03-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programari',
            fields=[
                ('ProgramareID', models.AutoField(primary_key=True, serialize=False)),
                ('Serviciu', models.CharField(max_length=256)),
                ('Data', models.DateField()),
                ('Ora', models.TimeField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticationApp.utilizatori')),
            ],
        ),
    ]
