# Generated by Django 5.0.3 on 2024-03-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
        ('programariApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programari',
            name='NumeUser',
            field=models.CharField(default='notSet', max_length=256),
        ),
        migrations.AddField(
            model_name='programari',
            name='Telefon',
            field=models.CharField(default='notSet', max_length=256),
        ),
        migrations.AlterField(
            model_name='programari',
            name='Serviciu',
            field=models.CharField(default='notSet', max_length=256),
        ),
        migrations.AlterField(
            model_name='programari',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticationApp.utilizatori'),
        ),
    ]
