# Generated by Django 5.0.3 on 2024-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programariApp', '0002_programari_numeuser_programari_telefon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLucru',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Zi', models.DateField()),
                ('PrimaOra', models.TimeField()),
                ('NumarOre', models.IntegerField()),
            ],
        ),
    ]
