# Generated by Django 5.0.3 on 2024-03-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicii',
            fields=[
                ('ServiciuID', models.AutoField(primary_key=True, serialize=False)),
                ('Nume', models.CharField(max_length=255)),
                ('Pret', models.IntegerField()),
                ('Descriere', models.CharField(max_length=256)),
            ],
        ),
    ]
